### ISSUE TITLE
Doesn't appear to work anymore? Stuck on login page

### ISSUE THREAD

**Issue by charlottetan** [swartanian/OptumHsaSaveItExport#18]
I keep getting stuck on fundingpremerawa's login screen, with the error message "Something went wrong. Please refresh your browser and try again.". I've spent several hours trying different things like disabling various arguments passed to the driver (in code), disabling CORS, etc. None of it worked. I used the manualLogin option.

I can log in as per normal on my regular Edge browser, so it is likely something specific to the webdriver.

109.0.1518.70 (Official build) (64-bit)

**Comment by charlottetan** [comment]
![flags](https://user-images.githubusercontent.com/4824630/215690191-921ce179-cf32-4532-bcd0-bb474167270f.PNG)

Screenshot showing all the args I tried toggling/disabling.

**Comment by swartanian** [comment]
@charlottetan  - still an issue, or fixed with your checkin/pr (I merged it).
